Improving styles, file permissions and adding bash scripts for communicating with master node

diff --git a/bin/v-delete-domain b/bin/v-delete-domain
--- a/bin/v-delete-domain
+++ b/bin/v-delete-domain
@@ -1,23 +1,24 @@
 #!/bin/bash
-# info: delete web/dns/mail domain
+# info: delete web/dns/mail domain + OpenLiteSpeed vhost
 # options: USER DOMAIN
 #
-# The function deletes web/dns/mail domain.
-
+# This removes domain configs from web/dns/mail and also from OpenLiteSpeed.
+# It reverses the changes done by v-add-domain-ols.
 
 #----------------------------------------------------------#
-#                    Variable&Function                     #
+#                    Variable & Function                   #
 #----------------------------------------------------------#
 
-# Argument definition
 user=$1
 domain=$2
 restart="${3-yes}"
 
+VESTA='/usr/local/vesta'
+export VESTA
+
 # Includes
 source $VESTA/func/main.sh
 source $VESTA/conf/vesta.conf
-
 
 #----------------------------------------------------------#
 #                    Verifications                         #
@@ -28,15 +29,14 @@ is_format_valid 'user' 'domain'
 is_object_valid 'user' 'USER' "$user"
 is_object_unsuspended 'user' 'USER' "$user"
 
-
 #----------------------------------------------------------#
-#                       Action                             #
+#                        Action                            #
 #----------------------------------------------------------#
 
 # Working on Web domain
 if [ ! -z "$WEB_SYSTEM" ]; then
     str=$(grep "DOMAIN='$domain'" $USER_DATA/web.conf)
-    if [  ! -z "$str" ]; then
+    if [ ! -z "$str" ]; then
         $BIN/v-delete-database-of-domain $domain
         domain_found='yes'
         $BIN/v-delete-web-domain $user $domain 'no'
@@ -47,7 +47,7 @@ fi
 # Working on DNS domain
 if [ ! -z "$DNS_SYSTEM" ]; then
     str=$(grep "DOMAIN='$domain'" $USER_DATA/dns.conf)
-    if [  ! -z "$str" ]; then
+    if [ ! -z "$str" ]; then
         domain_found='yes'
         $BIN/v-delete-dns-domain $user $domain 'no'
         check_result $? "can't delete dns" > /dev/null
@@ -57,19 +57,64 @@ fi
 # Working on Mail domain
 if [ ! -z "$MAIL_SYSTEM" ]; then
     str=$(grep "DOMAIN='$domain'" $USER_DATA/mail.conf)
-    if [  ! -z "$str" ]; then
+    if [ ! -z "$str" ]; then
         domain_found='yes'
         $BIN/v-delete-mail-domain $user $domain
         check_result $? "can't delete mail" > /dev/null
     fi
 fi
 
-# Checking domain search result
-if [ -z "$domain_found" ]; then
-    check_result $E_NOTEXISTS "domain $domain doesn't exist"
+#----------------------------------------------------------#
+#              OpenLiteSpeed Cleanup Section                #
+#----------------------------------------------------------#
+
+LSWS_ROOT="/usr/local/lsws"
+CONF_DIR="$LSWS_ROOT/conf"
+HTTPD_CONF="$CONF_DIR/httpd_config.conf"
+VHOSTS_DIR="$CONF_DIR/vhosts/$domain"
+LISTENERS=("Default" "Defaultssl")
+
+if [ -f "$HTTPD_CONF" ]; then
+    echo "🧹 Cleaning up OpenLiteSpeed configuration for '$domain'..."
+
+    # 1. Remove any 'map domain domain' lines from listeners
+    for LISTENER_NAME in "${LISTENERS[@]}"; do
+        if grep -q "listener $LISTENER_NAME" "$HTTPD_CONF"; then
+            sed -i "/listener $LISTENER_NAME {/,/}/{/map $domain $domain/d}" "$HTTPD_CONF"
+            echo "Removed listener mapping for '$domain' from '$LISTENER_NAME'"
+        fi
+    done
+
+    # 2. Remove the virtualHost block entirely
+    awk -v vhost="$domain" '
+        BEGIN {skip=0}
+        $0 ~ "virtualHost[[:space:]]+"vhost"[[:space:]]*{" {skip=1}
+        skip && /\}/ {skip=0; next}
+        !skip
+    ' "$HTTPD_CONF" > "${HTTPD_CONF}.tmp" && mv "${HTTPD_CONF}.tmp" "$HTTPD_CONF"
+
+    echo "Removed virtualHost block for '$domain'"
+
+    # 3. Remove vhost directory
+    if [ -d "$VHOSTS_DIR" ]; then
+        rm -rf "$VHOSTS_DIR"
+        echo "Deleted vhost directory: $VHOSTS_DIR"
+    fi
+
+    # 4. Reload OpenLiteSpeed
+    echo "Reloading OpenLiteSpeed..."
+    systemctl reload lsws
+    check_result $? "OpenLiteSpeed reload failed"
+
+    echo "✅ OpenLiteSpeed cleanup complete for '$domain'"
+else
+    echo "⚠️ OLS httpd_config.conf not found, skipping OLS cleanup."
 fi
 
-# Restarting services
+#----------------------------------------------------------#
+#                    Restart Services                      #
+#----------------------------------------------------------#
+
 $BIN/v-restart-web $restart
 check_result $? "can't restart web" > /dev/null
 
@@ -79,9 +124,8 @@ check_result $? "can't restart proxy" > /dev/null
 $BIN/v-restart-dns $restart
 check_result $? "can't restart dns" > /dev/null
 
-
 #----------------------------------------------------------#
-#                       Vesta                              #
+#                          Exit                            #
 #----------------------------------------------------------#
 
-exit
+exit 0
